name: The Itinerant Gourmet
favicon: null
layout_spectrum: 0.026075015543028712
typography_spectrum: 0.3742793737910688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c3b240'
    - '#7f2354'
    - '#a5791c'
    - '#bc8aa5'
  brandStrength: 0.998718643328175
  lightness: 0.6831512381322682
  saturation: 1
  rhythmicContrast: 0.9328460297547281
purpose: []
